apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-broker
  name: kafka-broker
spec:
  serviceName: kafka-headless-svc
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-broker
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-broker
    spec:
      containers:
        - env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HOSTNAME_COMMAND
              value: "route -n | awk '/UG[ \t]/{print $2}'"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://$(POD_NAME).kafka-headless-svc.default.svc.cluster.local:9094,EXTERNAL://$(HOST_IP):30092,FLINK://kafka-broker:9093"
            - name: KAFKA_CREATE_TOPICS
              value: tracks:1:1,default:1:1
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INTERNAL
            - name: KAFKA_LISTENERS
              value: INTERNAL://:9094,EXTERNAL://:9092,FLINK://:9093
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,FLINK:PLAINTEXT
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          image: wurstmeister/kafka:2.12-2.0.1
          imagePullPolicy: ""
          name: kafka-broker
          ports:
            - containerPort: 9092
            - containerPort: 9093
            - containerPort: 9094
          resources: {}
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: kafka-broker-hostpath0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: kafka-broker-hostpath0
status:
  replicas: 1
