apiVersion: v1
kind: Service
metadata:
  labels:
    app: eft-for-ssa
  name: kafka-headless-svc
spec:
  clusterIP: None
  ports:
  - name: internal
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    app: kafka
