apiVersion: v1
kind: Service
metadata:
  name: master-rest
spec:
  type: NodePort
  ports:
    - name: rest
      port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    io.kompose.service: master
