apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: worker
    spec:
      containers:
      - env:
        - name: MASTER_HOST
          value: master
        - name: ROLE
          value: worker
        image: spearw/eft-for-ssa:statefun-demonstration-example_master
        imagePullPolicy: ""
        name: worker
        ports:
        - containerPort: 6121
        - containerPort: 6122
        resources: {}
        volumeMounts:
        - mountPath: /checkpoint-dir
          name: worker-hostpath0
        - mountPath: /orekit-data
          name: worker-hostpath1
#        - name: flink-config-volume
#          mountPath: /opt/flink/conf/
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /checkpoint-dir
        name: worker-hostpath0
      - hostPath:
          path: /home/docker/orekit-data
        name: worker-hostpath1
#      - name: flink-config-volume
#        configMap:
#          name: flink-config
#          items:
#            - key: flink-conf.yaml
#              path: flink-conf.yaml
#            - key: log4j-console.properties
#              path: log4j-console.properties
status: {}
