apiVersion: v1
kind: Service
metadata:
  labels:
    app: eft-for-ssa
  name: zk-headless-svc
spec:
  clusterIP: None
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
    - name: follower
      port: 2888
      protocol: TCP
      targetPort: 2888
    - name: election
      port: 3888
      protocol: TCP
      targetPort: 3888
  selector:
    app: zookeeper
